spring.application.name=cinecritik-spring-demo
server.port=8080
spring.data.mongodb.uri=mongodb+srv://jsmayorgaj2008_db_user:uCulR0qmobJEcvkS@cinemetrick.2ehmbpc.mongodb.net/cinecritik?retryWrites=true&w=majority&appName=cinemetrick
spring.data.mongodb.database=cinecritik
